config/routes.rb
Rails.application.routes.draw do

  resources :range_subventions
  resources :addresses
  resources :notification_effects
  get 'calendar/index'

  # Public resources
  root to: 'homepage#index', format: false
  
  
  get 'authorize' => 'auth#gettoken'
  get '/redirect', to: 'events#redirect', as: 'redirect'
  get '/callback', to: 'events#callback', as: 'callback'
  get '/calendars', to: 'events#calendars', as: 'calendars'

  get '/lang/:lang', to: 'application#change_language', as: 'change_language'
  get '/show/:id', to: 'visitors#show', as: 'show'
  get '/update_holders', to: 'visitors#update_holders', as: 'update_holders'
  get '/inicio.do', to: 'uweb_access#uweb_sign_in'
  get '/agenda/:holder/:full_name', to: 'visitors#agenda', as: 'agenda'

  get '/faq', to: 'questions#index', as: 'faq'
  get '/websitemap', to: 'static_pages#websitemap', as: 'websitemap'

  post '/ws/agends', to: 'ws/agends#generic'
  post '/ws/agends/:personal_code', to: 'ws/agends#holder'

  resources :statistics, only: [:index]
  resources :statistics do
    get :lobbies, on: :collection
  end

  get '/code_of_conduct', to: 'static_pages#code_of_conduct', as: 'code_of_conduct'
  get '/accessibility', to: 'static_pages#accessibility', as: 'accessibility'

  get '/homepage', to: 'homepage#index', as: 'homepage'
  get 'registration_lobbies/index'
  get '/registration_lobbies', to: 'registration_lobbies#index', as: 'registration_lobbies'
  get '/visitors', to: 'visitors#index', as: 'visitors'
  get '/export_events', to: 'visitors#export_events', as: 'visitors_export_events'

  # Admin
  get "/admin", to: 'events#index', as: 'admin'
  
  #namespace :api do
    wash_out :servicio_integracion_bareg
  #end
  

  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :events do
    get :download, on: :collection
    get :clone, on: :member
    get :export_outlook, on: :member
    get :get_calendars, on: :member
  end
  
 
  resources :areas
  resources :activities
  resources :infringement_emails, only: [:new, :create]
  resources :holders do 
    get :active, on: :collection
    get :mail, on: :member
    post :send_mail, on: :member
    get :export_all, on: :collection
  end


  namespace :admin do
    resources :notifications, except: [:index, :new, :create, :destroy] do 
      get :active, on: :collection
      get :historic, on: :collection
      get :pre_recover, on: :member
      post :recover, on: :member
      get :pre_canceled, on: :member
      post :canceled, on: :member
      get :permited, on: :member
      get :manually_permited, on: :member
      get :recover_origin, on: :member
      post :update_notification, on: :member
    end
    resources :exports
    resources :parametrizations do
      post :change_view, on: :collection
      post :length_event_description, on: :collection
      post :send_email, on: :collection
    end
    resources :parametrizations, only: [:index]
    resources :manage_emails
    resources :users do 
      get :revert, on: :member
      get :assign_holder, on: :collection
      get :export_manages, on: :collection
      get :uweb, on: :collection
    end
    get 'passwords/edit', to: 'passwords#edit', as: 'edit_password'
    match 'passwords/update', to: 'passwords#update', as: 'update_password', via: [:patch, :put]
    resources :organizations do
      resources :agents
      resources :organization_interests, only: [:index]
      match 'interests_update', to: 'organization_interests#update', as: 'interests_update', via: [:patch, :put]
    end
    resources :organizations_links
    resources :questions
    post 'order_questions', to: 'questions#order', as: 'order_questions'

    resources :newsletters do
      member do
        post :deliver
      end
      get :users, on: :collection
    end
  end

  resources :positions do
    get :autocomplete_position_title, :on => :collection
  end
  get '/organizations/edit', to: 'organizations#edit', as: 'edit_organization'
  get '/organizations/destroy', to: 'organizations#destroy', as: 'destroy_organization'
  get '/organizations/new', to: 'organizations#new', as: 'new_organization'
  resources :organizations, except: [:new, :edit, :destroy] do
    get :autocomplete_organization_name, :on => :collection
    resources :represented_entities, only: :index, format: :json
    resources :agents, only: :index, format: :json
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get '*path' => redirect('/') unless Rails.env.development?

end

app/helpers/admin/organizations_helper.rb
module Admin
  module OrganizationsHelper
    def form_new_organization?
      params[:controller] == "admin/organizations" &&
        (params[:action] == "new" || params[:action] == "create")
    rescue => e
      begin
        Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def category_name(id)
      return if id.blank?
      Category.find(id).try(:name)
    rescue => e
      begin
        Rails.logger.error("COD-00002: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def address_number_types
      ["Num", "Km", "S/N"].sort.map { |rl| [rl, rl] }
    rescue => e
      begin
        Rails.logger.error("COD-00003: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def option_identifier_types
      ["DNI/NIF", "NIF", "NIE", "Pasaporte"].sort.map { |rl| [rl, rl] }
    rescue => e
      begin
        Rails.logger.error("COD-00004: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def show_partial?(partial)
      params[:show] ? params[:show] == partial && current_user.lobby? : false
    rescue => e
      begin
        Rails.logger.error("COD-00005: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def organization_attachments_download_dropdown_id(organization)
      "organization_#{organization.try(:id)}_attachments_dropdown"
    rescue => e
      begin
        Rails.logger.error("COD-00006: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def options_for_registered_lobby
      RegisteredLobby.where("name is not null AND name !='' ").order("CASE WHEN name='Ninguno' THEN 1 WHEN name='Otro' THEN 3 ELSE 2 END, name").map { |rl| [rl.name, rl.id] }.uniq
    rescue => e
      begin
        Rails.logger.error("COD-00007: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def options_for_provinces
      Province.where("name is not null AND name !='' ").order(name: :asc).map { |rl| [rl.name, rl.name] }.uniq
    rescue => e
      begin
        Rails.logger.error("COD-00008: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def options_for_countries
      Country.where("name is not null AND name !='' ").order(name: :asc).map { |rl| [rl.name, rl.name] }.uniq
    rescue => e
      begin
        Rails.logger.error("COD-00009: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def options_for_road_types
      RoadType.where("name is not null AND name !='' ").order(name: :asc).map { |rl| [rl.name, rl.name] }.uniq
    rescue => e
      begin
        Rails.logger.error("COD-00010: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
    end

    def permit_category_with_money(model = nil)
      return false if model.blank?
      model.category.category.name.to_s == "Entidad con ánimo de lucro"
    rescue => e
      begin
        Rails.logger.error("COD-00011: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
      false
    end

    def permit_category_without_money(model = nil)
      return false if model.blank?
      model.category.category.name.to_s == "Entidad sin ánimo de lucro" && model.category.name.to_s != "Agrupaciones de personas que se conformen como plataformas, movimientos, foros o redes ciudadanas sin personalidad jurídica, incluso las constituidas circunstancialmente"
    rescue => e
      begin
        Rails.logger.error("COD-00012: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
      rescue
      end
      false
    end

  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
  def organizations_index_subtitle
    if params[:order] == '1' || params[:order] == '2' || params[:order] == '3'
      t "organizations.results_title"
    else
      t "organizations.subtitle.default"
    end
  rescue => e
    begin
      Rails.logger.error("COD-00001: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_represented_entities_url_pattern(format)
    url = organization_represented_entities_url(organization_id: 999, format: format, protocol: protocol_for_urls)
    url.gsub('999', 'organization_id')
  rescue => e
    begin
      Rails.logger.error("COD-00002: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_agents_url_pattern(format)
    url = organization_agents_url(organization_id: 999, format: format, protocol: protocol_for_urls)
    url.gsub('999', 'organization_id')
  rescue => e
    begin
      Rails.logger.error("COD-00003: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_category_url_pattern
    url = organization_url(id: 999, format: :json, protocol: protocol_for_urls)
    url.gsub('999', 'organization_id')
  rescue => e
    begin
      Rails.logger.error("COD-00004: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def protocol_for_urls
    if Rails.env.development? || Rails.env.test?
      :http
    else
      :https
    end
  rescue => e
    begin
      Rails.logger.error("COD-00005: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def search_by_filter?
    (params[:interests].present? || params[:category].present? || params[:keyword].present?)
  rescue => e
    begin
      Rails.logger.error("COD-00006: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_status(organization)
    if !organization.expired_date.blank? && organization.expired_date < Time.zone.now
      '<span class="label alert">Caducado </span>'.html_safe
    elsif organization.canceled?
      '<span class="label alert">Baja </span>'.html_safe
    elsif organization.invalidated?
      if current_user.present? && current_user.admin?
        '<span class="label warning">Inhabilitado</span>'.html_safe
      else
        '<span class="label alert">Baja </span>'.html_safe
      end
    else
      '<span class="label success">Activo</span>'.html_safe
    end
  rescue => e
    begin
      Rails.logger.error("COD-00007: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_list_status(organization)
    if !organization.expired_date.blank? && organization.expired_date < Time.zone.now
      '<span class="label alert">Caducado </span>'.html_safe
    elsif organization.canceled? || organization.invalidated?
      '<span class="label alert">Baja </span>'.html_safe
    end
  rescue => e
    begin
      Rails.logger.error("COD-00008: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def events_as_lobby_by(organization)
    organization.events.where(lobby_activity: true, status: 2).count
  rescue => e
    begin
      Rails.logger.error("COD-00009: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

  def organization_back_button
    if current_user.present? && !params[:admin].blank? && params[:admin].to_s == "true"
      admin_organizations_path
    else
      organizations_path
    end
  rescue => e
    begin
      Rails.logger.error("COD-00010: [<#{self.class} - #{e.class}: #{e.message}] #{e.backtrace.join("\n")}")
    rescue
    end
  end

end

app/views/admin/organizations/_address_show.html.erb
<%if !model.try(:address).blank?%>
    <div class="row">
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.country') %></strong></p>
            <p><%= model.address.try(:country).blank? ? "<br>".html_safe : model.address.try(:country) %></p>
        </div>
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.province') %></strong></p>
            <p><%=  model.address.try(:province).blank? ? "<br>".html_safe : model.address.try(:province) %></p>
        </div>
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.town') %></strong></p>
            <p><%=  model.address.try(:town).blank? ? "<br>".html_safe : model.address.try(:town) %></p>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.address_type') %></strong></p>
            <p><%= model.address.try(:address_type).blank? ? "<br>".html_safe : model.address.try(:address_type) %></p>
        </div>
        <div class="small-12 medium-8 columns">
            <p><strong><%= t('backend.identifying_data.address') %></strong></p>
            <p><%= model.address.try(:address).blank? ? "<br>".html_safe :  model.address.try(:address) %></p>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.address_number_type') %></strong></p>
            <p><%= model.address.try(:address_number_type).blank? ? "<br>".html_safe : model.address.try(:address_number_type) %></p>
        </div>
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.number') %></strong></p>
            <p><%=  model.address.try(:number).blank? ? "<br>".html_safe : model.address.try(:number) %></p>
        </div>
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.gateway') %></strong></p>
            <p><%=model.address.try(:gateway).blank? ? "<br>".html_safe : model.address.try(:gateway) %></p>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.stairs') %></strong></p>
            <p><%= model.address.try(:stairs).blank? ? "<br>".html_safe : model.address.try(:stairs) %></p>
        </div>    
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.floor') %></strong></p>
            <p><%= model.address.try(:floor).blank? ? "<br>".html_safe : model.address.try(:floor) %></p>
        </div>
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.door') %></strong></p>
            <p><%= model.address.try(:door).blank? ? "<br>".html_safe : model.address.try(:door) %></p>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-4 columns">
            <p><strong><%= t('backend.identifying_data.postal_code') %></strong></p>
            <p><%= model.address.try(:postal_code).blank? ? "<br>".html_safe :  model.address.try(:postal_code) %></p>
        </div>        
        <div class="small-12 medium-8 columns">
            <p><strong><%= t('backend.identifying_data.email') %></strong></p>
            <p><%= model.address.try(:email).blank? ? "<br>".html_safe : model.address.try(:email) %></p>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-12 columns">
            <p><strong><%= t('backend.identifying_data.phones') %></strong></p>
            <p><%= model.address.try(:phones).blank? ? "<br>".html_safe : model.address.try(:phones) %></p>
        </div>           
    </div> 
<%end%>

app/views/admin/organizations/_address_show.pdf.erb
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.address_type') %></strong>
        <%= model.address.address_type %>
    </p>
</div>
<div class="small-12 medium-8 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.address') %></strong>
        <%= model.address.address %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.number') %></strong>
        <%= model.address.number %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.gateway') %></strong>
        <%= model.address.gateway %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.stairs') %></strong>
        <%= model.address.stairs %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.floor') %></strong>
        <%= model.address.floor %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.door') %></strong>
        <%= model.address.door %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.postal_code') %></strong>
        <%= model.address.postal_code %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.town') %></strong>
        <%= model.address.town %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.province') %></strong>
        <%= model.address.province %>
    </p>
</div>
<div class="small-12 medium-4 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.country') %></strong>
        <%= model.address.country %>
    </p>
</div>
 <div class="small-12 medium-6 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.phones') %></strong>
        <%= model.address.phones %>
    </p>
</div>
<div class="small-12 medium-6 columns mb10">
    <p>
        <strong><%= t('backend.identifying_data.email') %></strong>
        <%= model.address.email %>
    </p>
</div>

app/views/admin/organizations/_form.html.erb
<%= form_for [:admin, @organization], html: { class: 'organization-form' } do |f| %>

  <%= render 'admin/organizations/form/organization_errors', f: f %>
  <%= render 'admin/organizations/form/reference', f: f %>
  <%= render 'admin/organizations/form/data', f: f %>
  <%= render 'admin/organizations/form/legal_representant', f: f %>
  <%= render 'admin/organizations/form/notification_effect', f: f %>
  <%= render 'admin/organizations/form/user', f: f %>
  <%= render 'admin/organizations/form/lobby_data', f: f %>
  <%= render 'admin/organizations/form/represented_entities', f: f %>
  <%= render 'admin/organizations/form/agents', organization: @organization if !@organization.new_record? %>
  <%= render 'admin/organizations/form/terms', f: f %>
  <%= render 'admin/organizations/form/attachments', f: f %>
  <%= render 'admin/organizations/form/invalidate', f: f %>

  <div class="small-4 medium-3 large-2 column">
    <%= submit_tag t('backend.save'), class: "button radius success right" %>
  </div>

<% end %>

<%= javascript_include_tag 'organizations'%>

app/views/admin/organizations/edit.html.erb
<% if show_partial?('interests') %>
  <h1><%= t'backend.edit_title_interests' %></h1>
<% elsif show_partial?('agents') %>
  <h1><%= t'backend.edit_agents' %></h1>
<% else %>
  <h1>Editar Lobby</h1>
<% end %>
<%= render :partial => 'form' %>

app/views/admin/organizations/index.csv.erb
<%=

  exporter = OrganizationExporter.new true

  CSV.generate(col_sep: ';', encoding: 'ISO-8859-1') do |csv|
    csv << exporter.windows_headers

    @organizations.results.each do |organization|
      csv << exporter.windows_organization_row(organization)
    end
  end.html_safe
%>

app/views/admin/organizations/index.html.erb
<div class="row organizations-list">
  <div class="small-12 medium-8 column">
    <h1>
      <%= t('backend.companies') %> (<%= @organizations.count %>)
    </h1>
    <%= link_to t('backend.export'), admin_organizations_path(format: :csv,params: params),
               class: "button tiny radius success" if current_user.admin? %>
  </div>

  <div class=" small-12 medium-4 column">
    <%= link_to t('backend.new_company'),
              new_admin_organization_path,
              class: "button radius warning right" if can? :create, Organization %>
  </div>
</div>

<%= render 'admin_search_form' %>

<div class="small-12 medium-8 columns">
<%= page_entries_info @paginated_organizations, entry_name: t('backend.lobby') %>
<%= paginate @paginated_organizations %>
</div>
<%= form_tag admin_organizations_path, method: :get do %>
<%= hidden_field_tag :keyword, params[:keyword] %>
<%= hidden_field_tag :status_type, params[:status_type] %>
<%= hidden_field_tag :entity_type, params[:entity_type] %>
<div class="small-12 medium-4 columns">
  <label for="right-label" class="title-xs">
    <%= t("main.form.order_by") %>
  </label>
    <%= select_tag :order,
                  options_for_select({
                    t("main.form.name_asc") => 1,
                    t("main.form.name_desc") => 2,
                    t("main.form.inscription_date_asc") => 3,
                    t("main.form.inscription_date_desc") => 4
                  }, params[:order]),
                  include_blank: t("main.form.select"),
                  id: "search-order",
                  class: "select-sm",
                  onchange: "this.form.submit();" %>
</div>
<%end%>
<div class="small-12">
  <table class="small-12">
    <thead>
      <tr>
        <th><%= t('backend.lobby')%></th>
        <th><%= t('backend.lobby_created_at')%></th>
        <th><%= t('backend.lobby_renovation_at')%></th>
        <th><%= t('backend.lobby_expired_at')%></th>
        <th><%= t('backend.lobby_status')%></th>
        <th class="right"><%= t('backend.actions')%></th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th><%= t('backend.title')%></th>
        <th><%= t('backend.lobby_created_at')%></th>
        <th><%= t('backend.lobby_renovation_at')%></th>
        <th><%= t('backend.lobby_expired_at')%></th>
        <th><%= t('backend.lobby_status')%></th>
        <th class="right"><%= t('backend.actions')%></th>
      </tr>
    </tfoot>
    <tbody>
      <% @paginated_organizations.each do |organization| %>
      <tr id="<%= dom_id(organization) %>" >
        <td>
          <% if !organization.expired_date.blank? && Time.zone.now > organization.expired_date%>
            <i class="step fi-x size-24" style="color: red;"></i>
          <%end%>          
          <%= link_to organization.fullname, admin_organization_path(organization) %>
        </td>
        <td>
        <%= I18n.l organization.inscription_date, format: :short unless organization.inscription_date.blank? %>
        </td>
        <td>
        <%= I18n.l organization.renovation_date, format: :short unless organization.renovation_date.blank? %>
        </td>
        <td>
        <%if !organization.expired_date.blank? %>
          <%= I18n.l organization.expired_date, format: :short %>
        <%else%>
          <%= organization.set_expired_date.strftime("%d-%m-%Y") %>
        <%end%>
        </td>
        <td>
          <%= organization.status_type %>
        </td>
        <td class="right">
          <%if current_user.admin? %>
            <%= link_to admin_organization_agents_path(organization),
                      title: "Agentes" do %>
              <i class="step fi-torso size-24"></i>
            <% end %>
          <% end %>

          <%= link_to organization_path(organization, admin: "true"),
                      target: :_blank,
                      title: t('backend.lobby_show') do %>
            <i class="step fi-eye size-24"></i>
          <% end %>

          <%= link_to edit_admin_organization_path(organization),
                      title: t('backend.edit') do %>
            <i class="step fi-page-edit size-24"></i>
          <% end if can? :edit, organization %>

          <%= link_to admin_organization_path(organization),
                      method: :delete,
                      data: { confirm: t("backend.delete_confirm_lobby",name: organization.fullname) },
                      title: t('backend.delete') do %>
            <i class="step fi-page-delete size-24"></i>
          <% end if (can? :destroy, organization) && organization.status_type.to_s != t('backend.status_type.inactive') %>

          <% if organization.attachments.any? %>
            <%= link_to "#", title: t('backend.attachments_download'),
                        class: "organization-attachments-dropdown-link",
                        data: { dropdown: "#{organization_attachments_download_dropdown_id(organization)}" },
                        aria: { controls: "#{organization_attachments_download_dropdown_id(organization)}" } do %>
              <i class="step fi-archive size-24"></i>
            <% end %>

            <ul id="<%= organization_attachments_download_dropdown_id(organization) %>"
                class="organization-attachments-dropdown f-dropdown"
                data-dropdown-content aria-hidden="true" tabindex="-1">
              <% organization.attachments.each do |attachment| %>
                <li>
                  <%= link_to attachment.file.url, target: :_blank do %>
                    <i class="step fi-archive size-24"></i>
                    <%= attachment.file.original_filename %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          <% end %>
          <%#= link_to admin_organization_path(organization, format: :pdf), title: t('backend.get_pdf_identificator'), target: "blank" do %>
            <!--<i class="step fi-archive size-24"></i>-->
          <%#end%>
          
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @paginated_organizations %>

app/views/admin/organizations/new.html.erb
<div class="small-12 mt5 organizations-new">
  <h1><%= t('backend.new_organization_title')%></h1>
  <%= link_to t('backend.back'), admin_organizations_path , :class=> "button tiny radius" %>
</div>
<%= render "form" %>

app/views/admin/organizations/show.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title></title>
  </head>
  <body >
    
    <div id="main-content" class="main-content">

      <div class="row">
          <%= image_tag '/opt/AGEND/iam_agend/app/assets/images/madrid-lobby-pdf.png', class: 'header__imago', alt:'Lobbies, documento de inscripción', height: '90px'%>
      </div>
      <br><br>
      <div class="row">
        <p><%= t('backend.lobby_pdf_1', name: @organization.name, date: I18n.l(@organization.inscription_date, format: :short)) %>
        <% if !@organization.renovation_date.blank? %>
          <span style="color:red"><%= t('backend.lobby_pdf_2', date: I18n.l(@organization.renovation_date, format: :short))%>
        <% end %>
        <% if @organization.status_type == 'Caducado' %>
          <%= t('backend.lobby_pdf_3', date: I18n.l(@organization.expired_date, format: :short))%></span></p>
        <%end%>
      </div>
      <div class="row">
        <p><%= t('backend.lobby_pdf_4', name: @organization.name, id: @organization.id) %></p>
        <p><%= t('backend.lobby_pdf_5') %></p>
        <br>
        <p style="text-align:right">En Madrid, a <%= Time.zone.now.day %> de <%= Time.zone.now.month %> de <%= Time.zone.now.year %></p>
      </div>
    </div>
  </body>
</html>